mantisbt:
  image: xunmei/mantisbt:2.23.0
  ports:
    - "8989:80"
  links:
    - mysql
  volumes:
    - "/Users/fuyun/GitHub/scfido/mantisbt:/var/www/html"

mysql:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bugtracker
    - MYSQL_USER=mantisbt
    - MYSQL_PASSWORD=mantisbt