mantisbt:
  image: xunmei/mantisbt:2.7.0
  ports:
    - "8989:80"
  links:
    - mysql

mysql:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bugtracker
    - MYSQL_USER=mantisbt
    - MYSQL_PASSWORD=mantisbt